services:
  waste-app:
    build: .
    container_name: waste_app
    restart: unless-stopped  # Aplikacja wstanie sama po restarcie serwera
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Warsaw     # Ważne, żeby harmonogram działał w polskim czasie
    volumes:
      - .:/app