version: '3.8'

services:
  waste-app:
    build: .
    container_name: waste_app
    restart: unless-stopped  # Aplikacja wstanie sama po restarcie serwera
    ports:
      - "5000:5000"
    environment:
      - TZ=Europe/Warsaw     # Ważne, żeby harmonogram działał w polskim czasie
    volumes:
      # To mapuje pliki z serwera do kontenera.
      # Dzięki temu token.pickle, last_state.json i PDFy nie zginą po restarcie.
      - .:/app